import { IconType } from "react-icons";

import {
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiEnvelope,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineLink,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiBookBookmarkDuotone,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiTerminal,
  PiUserCircleDuotone
} from "react-icons/pi";

import {
  SiAlpinedotjs,
  SiAmazon,
  SiAngular,
  SiCloudflare,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFilament,
  SiFramer,
  SiGin,
  SiGit,
  SiGitlab,
  SiGo,
  SiGoland,
  SiHyprland,
  SiJavascript,
  SiKubernetes,
  SiLaravel,
  SiLivewire,
  SiManjaro,
  SiMantine,
  SiMariadb,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiRadixui,
  SiRailway,
  SiReact,
  SiRedis,
  SiShadcnui,
  SiSocketdotio,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVuedotjs
} from "react-icons/si";

import { FaDiscord, FaFacebook, FaGithub, FaLinkedin, FaPinterest, FaReddit, FaTelegram, FaThreads, FaWhatsapp, FaX, FaXTwitter, } from "react-icons/fa6";
import { FaSpotify } from "react-icons/fa";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  typescript: SiTypescript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  shadcn: SiShadcnui,
  mantine: SiMantine,
  radix: SiRadixui,
  motion: SiFramer,
  nodejs: SiNodedotjs,
  go: SiGo,
  gofiber: SiGin,
  gorm: SiGoland,
  websocket: SiSocketdotio,
  react: SiReact,
  python: SiPython,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  aws: SiAmazon,
  vercel: SiVercel,
  railway: SiRailway,
  cloudflare: SiCloudflare,
  manjaro: SiManjaro,
  hyprland: SiHyprland,
  terminal: PiTerminal,
  express: SiExpress,
  prisma: SiPrisma,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  redis: SiRedis,
  tailwind: SiTailwindcss,
  git: SiGit,
  gitlab: SiGitlab,
  laravel: SiLaravel,
  filament: SiFilament,
  php: SiPhp,
  mysql: SiMysql,
  mariadb: SiMariadb,
  vue: SiVuedotjs,
  angular: SiAngular,
  livewire: SiLivewire,
  alpine: SiAlpinedotjs,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  spotify: FaSpotify,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
